echo off
TBpad tbpad.dem
cls
echo This batch file shows a simple demonstration of TBpad in action:
echo Touch the keys shown to feed in the keystrokes indicated.
echo Hint: Start by touching "Date" and "Enter".
echo If the screen scrolls, just type PADDEMO again.
echo         здддддддддддддддддддддддддддддддддддддддддддддд©
echo         Ё здддддд© здддддд© здддддд© здддддд© здддддд© Ё
echo         Ё Ё  7   Ё Ё  8   Ё Ё  9   Ё Ё Date Ё Ё      Ё Ё
echo         Ё юдддддды юдддддды юдддддды юдддддды юдддддды Ё
echo         Ё здддддд© здддддд© здддддд© зддддддддддддддд© Ё
echo         Ё Ё  4   Ё Ё  5   Ё Ё  6   Ё Ё   Backspace   Ё Ё
echo         Ё юдддддды юдддддды юдддддды юддддддддддддддды Ё
echo         Ё здддддд© здддддд© здддддд© зддддддддддддддд© Ё
echo         Ё Ё  1   Ё Ё  2   Ё Ё  3   Ё Ё Unload TBpad  Ё Ё
echo         Ё юдддддды юдддддды юдддддды юддддддддддддддды Ё
echo         Ё здддддд© здддддд© здддддд© зддддддддддддддд© Ё
echo         Ё Ё  0   Ё Ё  /   Ё Ё  -   Ё Ё     Enter     Ё Ё
echo         Ё юдддддды юдддддды юдддддды юддддддддддддддды Ё
echo         юдддддддддддддддддддддддддддддддддддддддддддддды
